creates supervisor config toml
Signed-off-by: Collin McNeese <cmcneese@chef.io>

diff --git a/habitat/hooks/install b/habitat/hooks/install
--- a/habitat/hooks/install
+++ b/habitat/hooks/install
@@ -41,3 +41,11 @@ then
 else
   echo "not using systemd or initd under standard paths, exiting"
 fi
+
+# Verify that Supervisor config file is present
+if [ ! -f /hab/sup/default/config/sup.toml ]
+then
+  echo 'Attempting to create /hab/sup/default/config/sup.toml'
+  mkdir -p /hab/sup/default/config
+  hab sup run --generate-config > /hab/sup/default/config/sup.toml  ; echo 'Supervisor config file created.' || echo 'Could not generate config file.'
+fi
