moves default branch to main
Signed-off-by: Collin McNeese <cmcneese@chef.io>

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -2,9 +2,9 @@ name: hab_sup_service CI
 
 on:
   push:
-    branches: [ master ]
+    branches: [ main ]
   pull_request:
-    branches: [ master ]
+    branches: [ main ]
 
 jobs:
   build:
@@ -18,6 +18,7 @@ jobs:
       run: |
         hab origin key generate
         hab pkg build .
+        if [ ! -f results/last_build.env ] ; then echo "build failed!" ; exit 1 ; fi
       env:
         HAB_LICENSE: accept-no-persist
         HAB_ORIGIN: collinmcneese
